obj-$(CONFIG_AML_LCD_EXTERN) += lcd_extern.o
obj-$(CONFIG_AML_LCD_EXTERN) += lcd_extern_config.o
obj-$(CONFIG_AML_LCD_EXTERN) += ext_spi_dev.o
obj-$(CONFIG_AML_LCD_EXTERN) += ext_func.o
obj-$(CONFIG_AML_LCD_EXTERN) += ext_default.o
obj-$(CONFIG_AML_LCD_EXTERN) += mipi_default.o
obj-$(CONFIG_AML_LCD_EXTERN) += external_chip/
obj-$(CONFIG_AML_LCD_EXTERN_I2C_OLED) += i2c_oled.o
