obj-$(CONFIG_AML_LCD_EXTERN) += lcd_extern.o
obj-$(CONFIG_AML_LCD_EXTERN) += ext_spi_dev.o
obj-$(CONFIG_AML_LCD_EXTERN) += ext_func.o
obj-$(CONFIG_AML_LCD_EXTERN) += ext_default.o
obj-$(CONFIG_AML_LCD_EXTERN) += mipi_default.o
obj-$(CONFIG_AML_LCD_EXTERN_I2C_ANX6862_7911) += i2c_ANX6862_7911.o
obj-$(CONFIG_AML_LCD_EXTERN_I2C_RT6947) += i2c_RT6947.o
obj-$(CONFIG_AML_LCD_EXTERN_I2C_OLED) += i2c_oled.o
