/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef _ARCH_MESON_S1A_MEASURE_H_
#define _ARCH_MESON_S1A_MEASURE_H_

static const char* clk_msr_table[] = {
	[0] = "cts_sys_clk",
	[1] = "cts_axi_clk",
	[2] = "cts_rtc_clk",
	[3] = "eth_mppll_test",
	[4] = "p20_usb2_ckout",
	[6] = "sys_cpu_clk_div16",
	[8] = "cts_cecb_clk",
	[10] = "fclk_div5",
	[15] = "mpll_clk_50m",
	[18] = "hifi1_pll_clk",
	[19] = "hifi_pll_clk",
	[20] = "gp0_pll_clk",
	[22] = "eth_mppll_50m_ckout",
	[23] = "sys_pll_div16",
	[24] = "ddr_dpll_pt_clk",
	[25] = "mod_TSin_A_CLK_IN",
	[26] = "mod_TSin_B_CLK_IN",
	[32] = "cts_eth_clk125Mhz",
	[33] = "cts_eth_clk_rmii",
	[34] = "co_clkin_to_mac",
	[36] = "co_rx_clk",
	[37] = "co_tx_clk",
	[38] = "eth_phy_rxclk",
	[39] = "eth_phy_plltxclk",
	[40] = "ephy_test_clk",
	[50] = "vid_pll_div_clk_out",
	[51] = "cts_enci_clk",
	[52] = "cts_encp_clk",
	[53] = "cts_encl_clk",
	[54] = "cts_vdac_clk",
	[57] = "lcd_an_clk_ph2",
	[58] = "lcd_an_clk_ph3",
	[59] = "cts_hdmi_tx_pixel_clk",
	[60] = "cts_vdin_meas_clk",
	[61] = "cts_vpu_clk",
	[62] = "cts_vpu_clkb",
	[63] = "cts_vpu_clkb_tmp",
	[64] = "cts_vpu_clkc",
	[65] = "cts_vid_lock_clk",
	[66] = "cts_vapbclk",
	[67] = "cts_ge2d_clk",
	[76] = "hdmitx_tmds_clk",
	[77] = "cts_hdmitx_sys_clk",
	[78] = "cts_hdmitx_fe_clk",
	[80] = "cts_hdmitx_prif_clk",
	[81] = "cts_hdmitx_200m_clk",
	[82] = "cts_hdmitx_aud_clk",
	[84] = "audio_tohdmitx_mclk",
	[85] = "audio_tohdmitx_bclk",
	[86] = "audio_tohdmitx_lrclk",
	[87] = "audio__tohdmitx_spdif_clk",
	[88] = "htx_aes_clk",
	[93] = "cts_vdec_clk",
	[99] = "cts_hevcf_clk",
	[100] = "cts_demod_core_clk",
	[101] = "adc_extclk_in",
	[102] = "cts_demod_core_t2_clk",
	[103] = "adc_dpll_intclk",
	[104] = "adc_dpll_clk_b3",
	[105] = "s2_adc_clk",
	[106] = "deskew_pll_clk_div32_out",
	[107] = "cts_demod_32k_clk",
	[110] = "cts_sc_clk(smartcard)",
	[111] = "cts_sar_adc_clk",
	[113] = "cts_sd_emmc_C_clk(nand)",
	[116] = "gpio_msr_clk",
	[121] = "cts_ts_clk(temp sensor)",
	[130] = "audio_vad_clk",
	[131] = "acodec_dac_clk_x128",
	[132] = "audio_locker_in_clk",
	[133] = "audio_locker_out_clk",
	[134] = "audio_tdmout_c_sclk",
	[135] = "audio_tdmout_b_sclk",
	[136] = "audio_tdmout_a_sclk",
	[137] = "audio_tdmin_lb_sclk",
	[138] = "audio_tdmin_c_sclk",
	[139] = "audio_tdmin_b_sclk",
	[140] = "audio_tdmin_a_sclk",
	[141] = "audio_resamplea_clk",
	[142] = "audio_pdm_sysclk",
	[143] = "audio_spdifout_b_mst_clk",
	[144] = "audio_spdifout_mst_clk",
	[145] = "audio_spdifin_mst_clk",
	[147] = "audio_resampleb_clk",
	[166] = "pwm_d_clk",
	[167] = "pwm_c_clk",
	[168] = "pwm_b_clk",
	[169] = "pwm_a_clk",
	[176] = "rng_ring_0",
	[177] = "rng_ring_1",
	[178] = "rng_ring_2",
	[179] = "rng_ring_3",
	[180] = "sys_cpu_osc_ring[0](LVT30)",
	[181] = "sys_cpu_osc_ring[1](LVT30)",
	[182] = "dmc_osc_ring[0](SVT30)",
	[183] = "dmc_osc_ring[1](LVT35)",
	[184] = "top_osc_ring[0](LVT40)",
	[185] = "top_osc_ring[1](SVT35)",
	[186] = "top_osc_ring[2](HVT35)",
};

#endif
