# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_SARADC_AMLOGIC) += meson-saradc.o
obj-$(CONFIG_SARADC_MESON_C2) += meson-saradc-c2.o
obj-$(CONFIG_SARADC_MESON_G12A) += meson-saradc-g12a.o
obj-$(CONFIG_AMLOGIC_SARADC) += amlogic-saradc.o
