#
# (C) Copyright 2020
# hdmitx_mode.o hdmitx_hw_common.o hdmitx_format_para.o

#EXTRA_CFLAGS = -Idrivers/video/include/

obj-y += hdmitx_common.o

hdmitx_common-y := hdmitx_edid_parse.o hdmitx_edid_valid.o hdmitx_compliance.o
