#// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#/*
# * Copyright (c) 2023 Amlogic, Inc. All rights reserved.
# */


obj-$(CONFIG_AML_V3_USB_TOOl) += aml_v3_burn.o
aml_v3_burn-y  =  aml_dnl.o
aml_v3_burn-y +=  f_v3_usb_tool.o
aml_v3_burn-y +=  cmd_aml_dnl.o

