obj-$(CONFIG_AML_LCD) += lcd_vout.o
obj-$(CONFIG_AML_LCD) += lcd_common.o
obj-$(CONFIG_AML_LCD) += lcd_gpio.o
obj-$(CONFIG_AML_LCD) += lcd_debug.o
obj-$(CONFIG_AML_LCD) += lcd_unifykey.o
obj-$(CONFIG_AML_LCD) += lcd_cus_ctrl.o
obj-$(CONFIG_AML_LCD) += lcd_i2c_dev.o
obj-$(CONFIG_AML_LCD) += lcd_init_test.o

obj-$(CONFIG_AML_LCD) += lcd_vbyone.o
obj-$(CONFIG_AML_LCD) += lcd_lvds.o

obj-$(CONFIG_AML_LCD) += lcd_venc/
obj-$(CONFIG_AML_LCD) += lcd_clk/
obj-$(CONFIG_AML_LCD) += lcd_phy/
obj-$(CONFIG_AML_LCD) += lcd_dphy_ctrl.o

obj-$(CONFIG_AML_LCD_TCON) += lcd_tcon.o lcd_tcon_hw.o lcd_tcon_spi.o lcd_tcon_debug.o

obj-$(CONFIG_AML_LCD_TV) += lcd_tv/
obj-$(CONFIG_AML_LCD_TABLET) += lcd_tablet/

obj-$(CONFIG_AML_LCD_EXTERN) += lcd_extern/

obj-$(CONFIG_AML_LCD_BACKLIGHT) += backlight/
