#
# (C) Copyright 2020
#

#EXTRA_CFLAGS = -Idrivers/video/include/

obj-y += hdmitx21.o

hdmitx21-y := hdmitx_drv.o hdmitx_tvenc.o hdmitx_infoframe.o hdmitx_pktmgmt.o hdmitx_dump.o hdmitx_vrr.o
hdmitx21-y +=  hdmi_param.o hdmi.o hdmitx_frl_training.o hdmitx_ddc.o
obj-$(CONFIG_AML_DSC_ENC) += dsc/dsc_drv.o dsc/dsc_config.o dsc/dsc_hw.o dsc/dsc_debug.o

