
obj-$(CONFIG_AML_LCD) += lcd_clk_c3.o
obj-$(CONFIG_AML_LCD) += lcd_clk_a4.o
obj-$(CONFIG_AML_LCD) += lcd_clk_t5w.o
obj-$(CONFIG_AML_LCD) += lcd_clk_t7_t3.o
obj-$(CONFIG_AML_LCD) += lcd_clk_t5_t5d.o
obj-$(CONFIG_AML_LCD) += lcd_clk_utils.o
obj-$(CONFIG_AML_LCD) += lcd_clk_if.o
