obj-$(CONFIG_AML_LCD) += lcd_clk_s6.o
obj-$(CONFIG_AML_LCD) += lcd_clk_a4.o
obj-$(CONFIG_AML_LCD) += lcd_clk_t5m.o
obj-$(CONFIG_AML_LCD) += lcd_clk_t3x.o
obj-$(CONFIG_AML_LCD) += lcd_clk_txhd2.o
obj-$(CONFIG_AML_LCD) += lcd_clk_t6d.o
obj-$(CONFIG_AML_LCD) += lcd_clk_utils.o
obj-$(CONFIG_AML_LCD) += lcd_clk_if.o
