# SPDX-License-Identifier: GPL-2.0
#
obj-y += clk.o
obj-$(CONFIG_CLK_MESON_S4) += clk_meson_s4.o clk_measure.o
obj-$(CONFIG_CLK_MESON_A4) += clk_meson_a4.o clk_measure.o
obj-$(CONFIG_CLK_MESON_S1A) += clk_meson_s1a.o clk_measure.o
obj-$(CONFIG_CLK_MESON_S7) += clk_meson_s7.o clk_measure.o
