# SPDX-License-Identifier: GPL-2.0+

obj-y += clock/
obj-y += pinctrl/
obj-y += i2c/
obj-y += watchdog/
obj-y += adc/
obj-y += pwm/
obj-$(CONFIG_AML_MEDIA) += media/

obj-$(CONFIG_UNIFY_KEY_MANAGE) += keymanage/

obj-$(CONFIG_SECURE_STORAGE) += storagekey/

obj-$(CONFIG_SECURE_POWER_CONTROL) += power/

obj-$(CONFIG_MESON_LEDS_STATE_CONTROL) += leds/

obj-$(CONFIG_MESON_IR) += ir/

obj-$(CONFIG_AMLOGIC_TEE) += tee/

obj-$(CONFIG_AML_CRYPTO) += crypto/

obj-$(CONFIG_AML_MKL) += mkl/

obj-$(CONFIG_DM_MMC) += mmc/

obj-$(CONFIG_EFUSE) += efuse/

obj-$(CONFIG_DM_SPI) += spi/

obj-$(CONFIG_MTD) += mtd/

obj-$(CONFIG_SPI_FLASH_MTD) += mtd/spi/

obj-$(CONFIG_AMLOGIC_USB) += usb/host/

obj-$(CONFIG_AMLOGIC_USB) += usb/phy/

obj-$(CONFIG_AMLOGIC_USB) += usb/device/

obj-$(CONFIG_$(SPL_TPL_)CMD_JTAG) += jtag/
