# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_AML_MTD) += aml_rsv.o
obj-$(CONFIG_AML_STORAGE) += aml_storage.o
obj-$(CONFIG_AML_STORAGE) += aml_part.o
obj-$(CONFIG_AML_STORAGE) += page_info.o
obj-$(CONFIG_SPI_FLASH_MTD) += spi/
obj-$(CONFIG_MTD_SPI_NAND) += nand/spi/
obj-$(CONFIG_MESON_NFC) += nand/raw/
