# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_PINCTRL_MESON_S4)		+= pinctrl-meson-s4.o
obj-$(CONFIG_PINCTRL_MESON_A4)		+= pinctrl-meson-a4.o
obj-$(CONFIG_PINCTRL_MESON_S1A)		+= pinctrl-meson-s1a.o
obj-$(CONFIG_PINCTRL_MESON_S7)		+= pinctrl-meson-s7.o
obj-$(CONFIG_PINCTRL_MESON_T5M)		+= pinctrl-meson-t5m.o
obj-$(CONFIG_PINCTRL_MESON_S7D)		+= pinctrl-meson-s7d.o
obj-$(CONFIG_PINCTRL_MESON_S6)		+= pinctrl-meson-s6.o
obj-$(CONFIG_PINCTRL_MESON_T6D)		+= pinctrl-meson-t6d.o
