# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_PINCTRL_MESON_S4)		+= pinctrl-meson-s4.o
obj-$(CONFIG_PINCTRL_MESON_A4)		+= pinctrl-meson-a4.o
obj-$(CONFIG_PINCTRL_MESON_S1A)		+= pinctrl-meson-s1a.o
